### PR TITLE
#124: install python3.6 to rultor

### PR DESCRIPTION
**Pull request by vladarefiev**
PR for https://github.com/timelesslounge/timelessis/issues/124* add repository for installation 
- python3.6
- add python f-strings (which was added in python 3.6) for checking

### CODE REVIEW

**Comment by vladarefiev** [comment]
@emilianodellacasa according to https://github.com/timelesslounge/timelessis/pull/127
fixed, ready to merge

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@55d69b91-ec34-4bf1-baee-b9c4b56fbdad, thread: AsyncProc-6
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "wbs.xml" in "CF9LG1YCA" in 2min: java.util.concurrent.locks.ReentrantLock@62e21b4b[Locked by thread BkParallel-7]
```

[0.40.15](https://github.com/zerocracy/farm): CID: [ae934ab6-85fb-48d2-941c-33fc8bbc9284](https://www.0crat.com/footprint/CF9LG1YCA/ae934ab6-85fb-48d2-941c-33fc8bbc9284), Type: "Add job to WBS"

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#135` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
