### PR TITLE
Run React tests via Rultor.

### PR DESCRIPTION
**Pull request by pablopaul**
PR for #532 

* Install NodeJS and NPM dependencies
* Run React tests

### CODE REVIEW

**Comment by 0crat** [comment]
@pablopaul[/z](https://www.0crat.com/u/pablopaul) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please review this and merge or reject

**Comment by pablopaul** [comment]
@emilianodellacasa please merge

**Comment by emilianodellacasa** [comment]
@pablopaul Is `npm test` also providing coverage? If not, please add another puzzle to provide coverage

**Comment by pablopaul** [comment]
@emilianodellacasa I added a puzzle to report React test coverage, please merge.

**Comment by pablopaul** [comment]
@emilianodellacasa TravisCI build passes now

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0pdd** [comment]
@pablopaul the puzzle [#545](https://github.com/timelesslounge/timelessis/issues/545) is still not solved.

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@pablopaul could you please check why rultor is failing?

**Comment by pablopaul** [comment]
@emilianodellacasa I pushed a new commit which removes npm as os dep since it should be included in nodejs already.

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#533` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0pdd** [comment]
@pablopaul the puzzle [#unknown]() is still not solved.

**Pull request merged**
