### PR TITLE
#27 Reservation model

### PR DESCRIPTION
**Pull request by Vatavuk**
For #27, created Reservation model. The code has already been reviewed in PR #121.

@emilianodellacasa Can we merge this?

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#153](https://github.com/timelesslounge/timelessis/issues/153) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#153](https://github.com/timelesslounge/timelessis/issues/153) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/96b069a8-9c3f-4d71-a10c-bf0b877a9c5f); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#153` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by amihaiemil** [comment]
@rultor already reviewed, merge

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@vatavuk more single quotes

**Comment by Vatavuk** [comment]
@emilianodellacasa fixed, sry for the delay.

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by Vatavuk** [comment]
@emilianodellacasa fixed, please try again

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 40 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#153](https://github.com/timelesslounge/timelessis/issues/153) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by amihaiemil** [comment]
@ypshenychka Please mark this as "bad", since the review was done in the previous PR.

**Comment by ypshenychka** [comment]
@amihaiemil got it. Thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
