### PR TITLE
SettingsController for Reservations and puzzle

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #63

    * Moved Reservation Settings methods into a class
    * Created SettingsController and left puzzles

Already reviewed by @paulodamaso in #128 (initial PR was closed because the repo became public and had to be reforked)

### CODE REVIEW

**Comment by amihaiemil** [comment]
@emilianodellacasa I reforked and remade this PR which was reviewed already. Pls have a look :D

**Comment by 0crat** [comment]
Job [#161](https://github.com/timelesslounge/timelessis/issues/161) is now in scope, role is `REV`

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
This pull request [#161](https://github.com/timelesslounge/timelessis/issues/161) is assigned to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/11e47c52-bd8e-49f6-a97a-0be5e8e229d6); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@amihaiemil look at rultor log

**Comment by amihaiemil** [comment]
@emilianodellacasa do you happen to know which exactly are the warnings/errors that are causing the crash? Surely there can't be all of them since they were there before my changes :D

**Comment by emilianodellacasa** [comment]
@amihaiemil One of these has to be yours for sure:
```
************* Module timeless.reservations.controllers
timeless/reservations/controllers.py:12:4: C0111: Missing method docstring (missing-docstring)
timeless/reservations/controllers.py:12:43: W0613: Unused argument 'reservation_id' (unused-argument)
timeless/reservations/controllers.py:12:4: R0201: Method could be a function (no-self-use)
timeless/reservations/controllers.py:17:4: C0111: Missing method docstring (missing-docstring)
timeless/reservations/controllers.py:17:4: R0201: Method could be a function (no-self-use)
timeless/reservations/controllers.py:22:4: C0111: Missing method docstring (missing-docstring)
timeless/reservations/controllers.py:22:46: W0613: Unused argument 'settings' (unused-argument)
timeless/reservations/controllers.py:22:4: R0201: Method could be a function (no-self-use)
timeless/reservations/controllers.py:27:4: C0111: Missing method docstring (missing-docstring)
timeless/reservations/controllers.py:27:42: W0613: Unused argument 'reservation_id' (unused-argument)
timeless/reservations/controllers.py:27:58: W0613: Unused argument 'new_settings' (unused-argument)
timeless/reservations/controllers.py:27:4: R0201: Method could be a function (no-self-use)
timeless/reservations/controllers.py:32:4: C0111: Missing method docstring (missing-docstring)
timeless/reservations/controllers.py:32:42: W0613: Unused argument 'reservation_id' (unused-argument)
timeless/reservations/controllers.py:32:4: R0201: Method could be a function (no-self-use)
************* Module timeless.reservations.views
timeless/reservations/views.py:9:0: W0301: Unnecessary semicolon (unnecessary-semicolon)
timeless/reservations/views.py:56:0: C0305: Trailing newlines (trailing-newlines)
timeless/reservations/views.py:1:0: C0111: Missing module docstring (missing-docstring)
timeless/reservations/views.py:7:0: C0111: Missing class docstring (missing-docstring)
timeless/reservations/views.py:11:4: C0111: Missing method docstring (missing-docstring)
timeless/reservations/views.py:16:4: C0111: Missing method docstring (missing-docstring)
timeless/reservations/views.py:19:4: C0111: Missing method docstring (missing-docstring)
timeless/reservations/views.py:22:4: C0111: Missing method docstring (missing-docstring)
timeless/reservations/views.py:23:15: E1121: Too many positional arguments for method call (too-many-function-args)
timeless/reservations/views.py:29:4: R0201: Method could be a function (no-self-use)
timeless/reservations/views.py:39:4: R0201: Method could be a function (no-self-use)
timeless/reservations/views.py:43:4: R0201: Method could be a function (no-self-use)
timeless/reservations/views.py:49:4: R0201: Method could be a function (no-self-use)
```

;-)

**Comment by vladarefiev** [comment]
@amihaiemil rate is 7.81/10. minimal is 8.0

**Comment by amihaiemil** [comment]
@emilianodellacasa made some fixes and added some docstrings (pylint also complained about that). Score is now 8.15

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@amihaiemil just a 0.02 more :-)

**Comment by amihaiemil** [comment]
@emilianodellacasa funny, locally I get over 8. I'll recheck.

**Comment by amihaiemil** [comment]
@emilianodellacasa try to merge again? I've merged master and added docstrings, it is 8.2 now on my machine.

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@emilianodellacasa puzzle is now longer (>20 words), try again pls :D

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 21 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#161](https://github.com/timelesslounge/timelessis/issues/161) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@vladarefiev According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by vladarefiev** [comment]
@ypshenychka I did nothing. let quality bad i think

**Comment by ypshenychka** [comment]
@vladarefiev thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
