### PR TITLE
#72 initial table shapes views

### PR DESCRIPTION
**Pull request by krzyk**
#72 
* added initial table shapes views
* todo for continuation
* added `.idea` to exclusions in pdd, so it will work locally without any problems

### CODE REVIEW

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@55d69b91-ec34-4bf1-baee-b9c4b56fbdad, thread: AsyncProc-5
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "wbs.xml" in "CF9LG1YCA" in 2min: java.util.concurrent.locks.ReentrantLock@62e21b4b[Locked by thread BkParallel-7]
```

[0.40.15](https://github.com/zerocracy/farm): CID: [cb874bbf-45a0-40d0-b341-d3a2edf5b315](https://www.0crat.com/footprint/CF9LG1YCA/cb874bbf-45a0-40d0-b341-d3a2edf5b315), Type: "Add job to WBS"

**Comment by emilianodellacasa** [comment]
@0crat assign @cucumber007

**Comment by 0crat** [comment]
> @0crat assign @cucumber007 ([here](https://github.com/timelesslounge/timelessis/issues/136#issuecomment-461860586))

@emilianodellacasa The job [#136](https://github.com/timelesslounge/timelessis/issues/136) assigned to @cucumber007[/z](https://www.0crat.com/u/cucumber007), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/7e16092a-b03e-4162-a9ae-60b9d6ceaa9a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
@0crat assign REV @cucumber007

**Comment by 0crat** [comment]
> @0crat assign REV @cucumber007  ([here](https://github.com/timelesslounge/timelessis/issues/136#issuecomment-461867094))

@emilianodellacasa The job [#136](https://github.com/timelesslounge/timelessis/issues/136) assigned to @rev[/z](https://www.0crat.com/u/rev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/58324245-3939-49d2-94e6-0e6c8b8200b9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @rev[/z](https://www.0crat.com/u/rev) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/136#issuecomment-461873175))

@emilianodellacasa This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#136](https://github.com/timelesslounge/timelessis/issues/136) is [in scope](http://www.zerocracy.com/policy.html#14) for 39min
  * The role is `DEV`
  * The job is assigned to @rev[/z](https://www.0crat.com/u/rev) for [19min](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @krzyk[/z](https://www.0crat.com/u/krzyk): This user reported the ticket
    * @cucumber007[/z](https://www.0crat.com/u/cucumber007): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23136%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by emilianodellacasa** [comment]
@0crat role REV

**Comment by 0crat** [comment]
> @0crat role REV ([here](https://github.com/timelesslounge/timelessis/issues/136#issuecomment-461875475))

@emilianodellacasa Can't understand "role", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by emilianodellacasa** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/timelesslounge/timelessis/issues/136#issuecomment-461876068))

@emilianodellacasa Job [#136](https://github.com/timelesslounge/timelessis/issues/136) is already in scope

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @rev[/z](https://www.0crat.com/u/rev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#136](https://github.com/timelesslounge/timelessis/issues/136) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@emilianodellacasa Look like no code review was done here, right?

**Comment by emilianodellacasa** [comment]
@ypshenychka correct

**Comment by ypshenychka** [comment]
@emilianodellacasa thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
