### PR TITLE
For #342: Removed todo and methods that does not make sense anymore

### PR DESCRIPTION
**Pull request by paulodamaso**
For #342: I've forgot to remove the todo, and I've noticed that I didn't remove the procedural methods that were supressed by `SyncedTable` implementation.
- Removed todo 
- removed methods that does not make sense anymore

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#399](https://github.com/timelesslounge/timelessis/issues/399) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#399](https://github.com/timelesslounge/timelessis/issues/399) is assigned to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/28b227c1-2104-4818-98f4-a37a970af63d); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#399](https://github.com/timelesslounge/timelessis/issues/399) is not in the agenda of @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), can't inspect

**Comment by 0crat** [comment]
The job [#399](https://github.com/timelesslounge/timelessis/issues/399) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@vladarefiev According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by vladarefiev** [comment]
@paulodamaso @emilianodellacasa Why did we remove it?

that methods are called from this place - https://github.com/timelesslounge/timelessis/blob/master/timeless/poster/tasks.py#L40

**Comment by vladarefiev** [comment]
@paulodamaso I can't find right PR, pls provide it here

**Comment by paulodamaso** [comment]
@vladarefiev What can I do to help you?

**Comment by vladarefiev** [comment]
@paulodamaso attach here PR , where you reimplemented this logic https://github.com/timelesslounge/timelessis/pull/399/files#diff-62f842daf486f4ed9451763a2386118eL133

**Comment by vladarefiev** [comment]
@paulodamaso I just can't find decision of both tasks https://github.com/timelesslounge/timelessis/issues/345 and https://github.com/timelesslounge/timelessis/issues/342

**Comment by ypshenychka** [comment]
@vladarefiev ping

**Comment by vladarefiev** [comment]
@ypshenychka we need to revert this one. I did nothing

**Comment by ypshenychka** [comment]
@vladarefiev thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@paulodamaso 2 puzzles [#385](https://github.com/timelesslounge/timelessis/issues/385), [#485](https://github.com/timelesslounge/timelessis/issues/485) are still not solved.

**Comment by 0pdd** [comment]
@paulodamaso the puzzle [#485](https://github.com/timelesslounge/timelessis/issues/485) is still not solved; solved: [#385](https://github.com/timelesslounge/timelessis/issues/385).

**Comment by 0pdd** [comment]
@paulodamaso all 2 puzzles are solved here: [#385](https://github.com/timelesslounge/timelessis/issues/385), [#485](https://github.com/timelesslounge/timelessis/issues/485).

**Pull request merged**
