### PR TITLE
#37 Setup of DB integration tests

### PR DESCRIPTION
**Pull request by bkuzmic**
For #37:

- Setting fixtures for database integration tests - using `pytest-flask-sqlalchemy` module
- Applying migrations automatically on test database before tests start
- Example is in: `test_employees.test_insert_employee` method

### CODE REVIEW

**Comment by ypshenychka** [comment]
@amihaiemil thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
