### PR TITLE
#15 Item Model + Test + Puzzle

### PR DESCRIPTION
**Pull request by marceloamadeu**
PR for #15

- Added Item Model
- Left puzzle for continuing implementation
- Migration has not been added since it is not possible to generate.

### CODE REVIEW

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job [#139](https://github.com/timelesslounge/timelessis/issues/139) is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#139` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#139](https://github.com/timelesslounge/timelessis/issues/139) is now out of scope

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#139` doesn't exist in WBS, can't create order

**Pull request merged**
