### PR TITLE
Issue #267 - add new puzzle to fix CommentView

### PR DESCRIPTION
**Pull request by soin08**
To fix integration tests on comments, CommentView has to work. This PR creates a new puzzle to solve https://github.com/timelesslounge/timelessis/issues/267

### CODE REVIEW

**Comment by 0crat** [comment]
@soin08[/z](https://www.0crat.com/u/soin08) this pull request is too small, just 3 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please review this and merge or reject

**Comment by soin08** [comment]
Decided not to do this task

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#516` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
