### PR TITLE
#214 class views for Table, removed puzzles

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #214 

* refactored all endpoint procedures from Tables ``views.py`` to use the existing generic view classes
* removed ticket puzzle
* removed old puzzle (the one originating from ticket ``112``) because it was also obsolete (see discussion [here](https://github.com/timelesslounge/timelessis/issues/170))

**Edit**: I'm not exactly sure whether the HTML pages (navigation from Location views, for instance) are implemented or I should leave a puzzle.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#466](https://github.com/timelesslounge/timelessis/issues/466) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#466](https://github.com/timelesslounge/timelessis/issues/466) is assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/71cea842-1ba7-405e-bd2f-27564f09889d); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by amihaiemil** [comment]
@vryazanov can you also have a look over this PR? thanks :)

**Comment by vryazanov** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#466](https://github.com/timelesslounge/timelessis/issues/466) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@vryazanov According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by vryazanov** [comment]
@ypshenychka confirm. agree that quality is bad :)

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
