### PR TITLE
#379 added sortable table for reservations

### PR DESCRIPTION
**Pull request by krzyk**
#379 
* added sorting capability to reservations
* converted reservation display to table

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#550](https://github.com/timelesslounge/timelessis/issues/550) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#550](https://github.com/timelesslounge/timelessis/issues/550) is assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/9c3cd2a1-9b10-41fc-9869-938da8db5078); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by zverovich** [comment]
@0crat refuse

**Comment by 0crat** [comment]
@zverovich[/z](https://www.0crat.com/u/zverovich) I see that you unassigned this issue; the order is still assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/550#issuecomment-485644326))

@zverovich The user @vryazanov[/z](https://www.0crat.com/u/vryazanov) resigned from [#550](https://github.com/timelesslounge/timelessis/issues/550), please stop working. Reason for job resignation: Order was cancelled

**Pull request closed without merging**
