### PR TITLE
#22 User access control

### PR DESCRIPTION
**Pull request by Vatavuk**
For #22 , started user access control implementation. Left a lot of puzzles.

The idea is to have class based view that will handle authorization and will
be used by all views that need access control.
Like this:
```python
class Company(SecuredView):

       resource="company"
        
       def get(self, company_id):
         #...
```
We only need to specify resource and the rest will be done by `access_control` module.

### CODE REVIEW

**Comment by Vatavuk** [comment]
@emilianodellacasa will fix it

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by Vatavuk** [comment]
@emilianodellacasa I will close this PR and reopen a new one, just to set project to a new fork

**Comment by emilianodellacasa** [comment]
@vatavuk Thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#109](https://github.com/timelesslounge/timelessis/issues/109) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

Only two issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by amihaiemil** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@amihaiemil thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request closed without merging**
