### PR TITLE
#124: add repo to rultor for python3.6 installation

### PR DESCRIPTION
**Pull request by vladarefiev**
PR for https://github.com/timelesslounge/timelessis/issues/124

- add repository for installation python3.6
- add python f-strings (which was added in python 3.6) for checking

### CODE REVIEW

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@55d69b91-ec34-4bf1-baee-b9c4b56fbdad, thread: AsyncProc-5
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "wbs.xml" in "CF9LG1YCA" in 2min: java.util.concurrent.locks.ReentrantLock@62e21b4b[Locked by thread BkParallel-7]
```

[0.40.15](https://github.com/zerocracy/farm): CID: [a49120da-bcf7-4140-a5df-6d5630382a60](https://www.0crat.com/footprint/CF9LG1YCA/a49120da-bcf7-4140-a5df-6d5630382a60), Type: "Close job"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@55d69b91-ec34-4bf1-baee-b9c4b56fbdad, thread: AsyncProc-5
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "orders.xml" in "CF9LG1YCA" in 2min: java.util.concurrent.locks.ReentrantLock@62e21b4b[Locked by thread BkParallel-7]
```

[0.40.15](https://github.com/zerocracy/farm): CID: [a49120da-bcf7-4140-a5df-6d5630382a60](https://www.0crat.com/footprint/CF9LG1YCA/a49120da-bcf7-4140-a5df-6d5630382a60), Type: "Close job"

**Comment by amihaiemil** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/127#issuecomment-462053199))

@amihaiemil This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#127](https://github.com/timelesslounge/timelessis/issues/127) is [in scope](http://www.zerocracy.com/policy.html#14) for 4days
  * The role is `REV`
  * The job is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) for [4days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) will get 25% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @vladarefiev[/z](https://www.0crat.com/u/vladarefiev): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23127%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by amihaiemil** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/127#issuecomment-462054880))

@amihaiemil The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#127](https://github.com/timelesslounge/timelessis/issues/127), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
This pull request [#127](https://github.com/timelesslounge/timelessis/issues/127) is assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/8bbcabc4-06c0-48d6-8d88-62bce5edb4f6); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by amihaiemil** [comment]
@emilianodellacasa Can you take this PR out of scope? 0crat had some issues and thinks its still open.

**Comment by emilianodellacasa** [comment]
@0crat out

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/timelesslounge/timelessis/issues/127#issuecomment-462059188))

@emilianodellacasa The job [#127](https://github.com/timelesslounge/timelessis/issues/127) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@amihaiemil Look like PR is now assigned not to you, but as far as no issues were found during code review, I don't think it's necessary to reassign it back to you though. Quality will still be bad. Agree?

**Comment by amihaiemil** [comment]
@ypshenychka yes, sure :)

**Comment by ypshenychka** [comment]
@amihaiemil thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request closed without merging**
