### PR TITLE
#168 less pylint excludes

### PR DESCRIPTION
**Pull request by krzyk**
#168 
* removed exclusion of whole module
* added exclusion of specific classes that have members dynamically generated

### CODE REVIEW

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please review this and merge or reject

**Comment by emilianodellacasa** [comment]
@krzyk for some reason Travis is failing

**Comment by krzyk** [comment]
@emilianodellacasa Classical heisenbug :) -> #365

**Comment by krzyk** [comment]
@emilianodellacasa so sometimes you will see fails in travis and rultor that are not related to the changes

**Comment by emilianodellacasa** [comment]
@krzyk Actually it is the very first time I see travis failing that way; also, I merged a PR 5 minutes ago and had no problem both in rultor and travis

**Comment by krzyk** [comment]
@emilianodellacasa I saw this two times already when running tests in https://github.com/timelesslounge/timelessis/pull/333, just after I used EmployeeFactory

**Comment by krzyk** [comment]
@emilianodellacasa Please check for yourself, I run on master branch:
```
for i in `seq 1000`; do pytest tests/integration/it_other_privilages_test.py > result_$i; done
```

I did something like that and I have so far out of `657`, `82` failed with EmployeeFactory, so it gives ~12 % failure rate.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please review this and merge or reject

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#364` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dd1d7898-ef5b-482a-9db4-19a9447b7d09, thread: pool-7-thread-8
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:timelesslounge/timelessis#364] declared for identity constraint of element "blanks".
```

[0.42.1](https://github.com/zerocracy/farm): CID: [7a24d85c-aa95-47c1-a428-b97dd6fe68a3](https://www.0crat.com/footprint/CF9LG1YCA/7a24d85c-aa95-47c1-a428-b97dd6fe68a3), Type: "Close job"

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#364` is not assigned, can't get performer

**Pull request merged**
