### PR TITLE
#376 Implement synchronization between Poster and Database forTables

### PR DESCRIPTION
**Pull request by ebercamargo**
#376 
- Implement synchronization between Poster and Database forTables

### CODE REVIEW

**Comment by ebercamargo** [comment]
@emilianodellacasa As requested.

**Comment by 0crat** [comment]
@ebercamargo[/z](https://www.0crat.com/u/ebercamargo) this pull request is too small, just 0 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please review this and merge or reject

**Comment by emilianodellacasa** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/511#issuecomment-471186537))

@emilianodellacasa Job `gh:timelesslounge/timelessis#511` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#511` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
