### PR TITLE
#376 Implement synchronization between Poster and Database for Tables

### PR DESCRIPTION
**Pull request by ebercamargo**
- Implement synchronization between Poster and Database for Tables
- Test for Implement

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#487](https://github.com/timelesslounge/timelessis/issues/487) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#487](https://github.com/timelesslounge/timelessis/issues/487) is assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/97993252-7a98-46bb-af08-d32dac7d448d); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 17 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#487](https://github.com/timelesslounge/timelessis/issues/487) is not in the agenda of @vryazanov[/z](https://www.0crat.com/u/vryazanov), can't inspect

**Comment by 0crat** [comment]
The job [#487](https://github.com/timelesslounge/timelessis/issues/487) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@vryazanov According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by ypshenychka** [comment]
@ebercamargo According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to

Please add link to issue into PR's description.

**Comment by ebercamargo** [comment]
> 
> 
> @ebercamargo According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
> 
> > Pull request description explains the solution proposed and contains a link to the original ticket it is related to
> 
> Please add link to issue into PR's description.

@ypshenychka adjusted...

**Comment by vryazanov** [comment]
@ypshenychka  confirm

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by ebercamargo** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/487#issuecomment-471039736))

@ebercamargo This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#487](https://github.com/timelesslounge/timelessis/issues/487) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23487%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ebercamargo** [comment]
@ypshenychka ping

**Comment by ypshenychka** [comment]
@ebercamargo what? :)

**Comment by ebercamargo** [comment]
> 
> 
> @ebercamargo what? :)

@ypshenychka i beleave that, I believe that this issue should be OK in my Agenda. Does needed a new any action?

**Comment by ypshenychka** [comment]
@ebercamargo You should remove puzzle so that PDD can close the issue you were working one (#376).

**Pull request merged**
