### PR TITLE
#86 Travis and Code Climate configuration

### PR DESCRIPTION
**Pull request by bkuzmic**
For #86:

- Adding `.travis.yml` to build and test with coverage
- Adding `.codeclimate.yml` to run code checks and analysis

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#252](https://github.com/timelesslounge/timelessis/issues/252) is now in scope, role is `REV`

**Comment by bkuzmic** [comment]
@emilianodellacasa Please take a look why there are two builds (point to the same build actually) are triggered on Travis.

**Comment by 0crat** [comment]
This pull request [#252](https://github.com/timelesslounge/timelessis/issues/252) is assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/54d11f10-941b-45d4-86ae-e72b7d5c0d02); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by vryazanov** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@bkuzmic Ok, I solved the double build problem on the configuration (we will see the effects on the next build I guess); however, I see that the one we will keep is always pending, even though the job is actually finished (see in details);

I think I will merge it and see how it behaves on next PR, if there is something missing we will fix it.

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 10 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#252](https://github.com/timelesslounge/timelessis/issues/252) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by vryazanov** [comment]
@ypshenychka I confirm that will try to find 3 problems next time. I agree that quality is bad :)

**Comment by ypshenychka** [comment]
@vryazanov And here again :) You don't give me a chance to do my job! )) Thanks!

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
