### PR TITLE
#236: remove puzzle

### PR DESCRIPTION
**Pull request by vladarefiev**
#236: 
- Remove puzzle, because I forgot do it in https://github.com/timelesslounge/timelessis/pull/435 . Work is done

### CODE REVIEW

**Comment by vladarefiev** [comment]
@emilianodellacasa My bad, forgot remove puzzle in PR

**Comment by 0crat** [comment]
@vladarefiev[/z](https://www.0crat.com/u/vladarefiev) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please review this and merge or reject

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#454` is not assigned, can't get performer

**Pull request merged**
