### PR TITLE
#175 add manager role priviledges

### PR DESCRIPTION
**Pull request by krzyk**
#176 
* added manager role priviledges
* added tests to cover that
* todo for checking also roles

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#280](https://github.com/timelesslounge/timelessis/issues/280) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#280](https://github.com/timelesslounge/timelessis/issues/280) is assigned to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/128bd980-15c0-4201-906e-0747077e0259); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#280](https://github.com/timelesslounge/timelessis/issues/280) is now out of scope

**Comment by 0crat** [comment]
Job [#280](https://github.com/timelesslounge/timelessis/issues/280) is not in the agenda of @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), can't inspect

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by vladarefiev** [comment]
@krzyk is it realy closed?

**Comment by krzyk** [comment]
@vladarefiev Yeah, I added wrong commit, so I created a new PR

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/280#issuecomment-465031080))

@ypshenychka This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#280](https://github.com/timelesslounge/timelessis/issues/280) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 1days
  * @vladarefiev[/z](https://www.0crat.com/u/vladarefiev) will receive 20 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23280%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@vladarefiev Looks like no work was done here, right?

**Comment by vladarefiev** [comment]
@ypshenychka correct.

**Comment by ypshenychka** [comment]
@vladarefiev thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request closed without merging**
