### PR TITLE
#155 Refactoring tests. Fixing pytest fixtures to make test fast again

### PR DESCRIPTION
**Pull request by bkuzmic**
For #155:

- Moving tests that use `app.test_client` to integration folder
- Speeding up tests by fixing pytest fixtures - now after each method session is roll-backed as long as test uses `db_session` fixture)

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#258](https://github.com/timelesslounge/timelessis/issues/258) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#258](https://github.com/timelesslounge/timelessis/issues/258) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/04d20195-486f-4f68-a205-9845f03304f9); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#258` already assigned to @amihaiemil, can't assign to @vryazanov

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#258` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#258` already assigned to @amihaiemil, can't assign to @vryazanov

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#258` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by amihaiemil** [comment]
@bkuzmic This PR has 20 changed files and they are not only moved around, I see you also changed code. Were the code changes necessary? If not, then undo them and open a new ticket. 

If the code changes are necessary then make a new PR only with part of the relocated tests which don't require code change and leave a puzzle for the rest.

I'm sorry, but this PR is too big, I would say.

**Comment by emilianodellacasa** [comment]
@bkuzmic It is true, PR is quite big but I see that the changes in code do not affect the code, but the quality of the code.

As long as tests are all green and pylint do not complain, I am good with that.

@amihaiemil you are REV, you tell me what to do

**Comment by bkuzmic** [comment]
@amihaiemil @emilianodellacasa  The task was to move the tests that are integration to integration folder and to put model tests to `test_models.py` - hence 20 files are changed. Also, the code needed to be changed in order to conform to integration tests where db_session should be rollbacked. Speed up changes don't actually belong here, but I had to put them somewhere.

**Comment by amihaiemil** [comment]
@bkuzmic Well, if it were my project, I'd definetely reject the PR, it's simply too big. But if everything works, I don't want to waste project resources just for the sake of methodology...

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by bkuzmic** [comment]
@amihaiemil I agree that the PR is too big. I'm still balancing trying to find the right size. This task of moving the tests and fixing (not including speed ups) did't actually took too much time (around 30 minutes).

**Comment by bkuzmic** [comment]
@emilianodellacasa What happened with Travis CI and Coverage? I don't see the checks for that.

**Comment by amihaiemil** [comment]
@bkuzmic @emilianodellacasa well, sh*t. I forgot to look for puzzles. At least [one](https://github.com/timelesslounge/timelessis/issues/245#issuecomment-463963438) has been removed.  And I don't see a new ticket (supposedly from the new location) for it. 

@bkuzmic Can you make another PR with the puzzles that were removed?

**Comment by emilianodellacasa** [comment]
@bkuzmic Now they are back. Please check puzzles please as @amihaiemil said

**Comment by bkuzmic** [comment]
@emilianodellacasa Sorry about the puzzles. These ones are moved in files: #234, #241

**Comment by emilianodellacasa** [comment]
@bkuzmic Did you check no puzzle has been lost?

**Comment by bkuzmic** [comment]
@emilianodellacasa I see that, even PR is merged, puzzles are still open.

**Comment by 0crat** [comment]
Job was finished in 16 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#258](https://github.com/timelesslounge/timelessis/issues/258) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by amihaiemil** [comment]
@bkuzmic There is this [one](https://github.com/timelesslounge/timelessis/issues/245#issuecomment-463963438) which has been removed.

**Comment by bkuzmic** [comment]
@amihaiemil @emilianodellacasa  It seems that I replaced the existing integration test with unit test, or file: it_poster_test.py with test_poster.py. I'll create a new PR to fix this.

**Comment by ypshenychka** [comment]
@amihaiemil  According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by amihaiemil** [comment]
@ypshenychka confirmed

**Comment by ypshenychka** [comment]
@amihaiemil thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by bkuzmic** [comment]
@emilianodellacasa Here is the PR that fixes problems with tests and puzzle: #268

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
