### PR TITLE
#216 Fix template caching

### PR DESCRIPTION
**Pull request by vryazanov**
#216 

Use cache directive only in base template

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#220](https://github.com/timelesslounge/timelessis/issues/220) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#220](https://github.com/timelesslounge/timelessis/issues/220) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/e8c40ff2-575d-4b91-bf0f-91d3c4a1aa47); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by amihaiemil** [comment]
@emilianodellacasa nothing to view here, please merge

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by vryazanov** [comment]
@emilianodellacasa @amihaiemil I guess you should have asked me about caching CRUD forms and user's data. Because we are caching the whole base template, will users see the same cached HTML on all pages or not? I guess, they will. Just cache directive does not work yet, since Redis is not installed, as I now, so we cannot check how it actually works. But looks like it's a different story :)

**Comment by amihaiemil** [comment]
@vryazanov well, in this ticket you simply changed a number which was already in place. What that number does exactly is a matter for a new ticket -- if you think it's not a good solution, open an Issue and ask the ARC. 

Right now, maybe add a comment there and mention what 600 means exactly? Is it minutes, hours or days?

**Comment by 0crat** [comment]
Job was finished in 34 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#220](https://github.com/timelesslounge/timelessis/issues/220) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by amihaiemil** [comment]
@ypshenychka confirmed

**Comment by ypshenychka** [comment]
@amihaiemil thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
