### PR TITLE
Integrate React.

### PR DESCRIPTION
**Pull request by pablopaul**
PR for #514 

* Setup React dependencies
* Add React development workflow to readme
* Puzzle to add React test execution to CI

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#519](https://github.com/timelesslounge/timelessis/issues/519) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#519](https://github.com/timelesslounge/timelessis/issues/519) is assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/4e7e42f4-fd00-4b90-bcc9-6d6f57089f3b); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by vryazanov** [comment]
@emilianodellacasa  @pablopaul If I would implement SPA application, I will do the same way as it's implemented in this PR using `create-react-app` package. but as far as I understand we need something different and this structure doesnt fit to us. 

I have only negative experience using angluar/react + backend templates and keeping FE / BE in one repository. I admit I could doing something wrong, so I cannot review this MR, just do not know how to implement it the best way

**Comment by pablopaul** [comment]
@vryazanov you wrote

>  but as far as I understand we need something different and this structure doesnt fit to us.

Why does this structure does not fit?
What do we need then exactly?

**Comment by pablopaul** [comment]
@emilianodellacasa as `ARC` shoudl decide please

**Comment by vryazanov** [comment]
> @vryazanov you wrote
> 
> > but as far as I understand we need something different and this structure doesnt fit to us.
> 
> 1. Why does this structure does not fit exactly?
> 2. What do we need instead exactly?

@pablopaul  
1) Since we are already using back-end templates, so SPA structure is not for us.
2) Actually I have no good ideas how it should look like :)

**Comment by emilianodellacasa** [comment]
@pablopaul @vryazanov It seems to me that files are stored in a different dir hierarchy, how it will be run (in the same server or in another one) it's a different thing. Let's keep this approach

**Comment by vryazanov** [comment]
@emilianodellacasa I just would say that current implementation is focused on SPA application with only one entry point - `frontend/src/index.js`. If we are going to use react in templates we should inject react to our base template.

**Comment by pablopaul** [comment]
@vryazanov as you are not proposing anything concrete I could do to improve the existing React integration and the `ARC` already approved the current approach (see above), please approve the PR so I can continue to work on it, thanks.

**Comment by vryazanov** [comment]
@rultor merge

**Comment by vryazanov** [comment]
> @vryazanov as you are not proposing anything concrete I could do to improve the existing React integration and the `ARC` already approved the current approach (see above), please approve the PR so I can continue to work on it, thanks.

@pablopaul I just though the way of integration is quite obvious. the same way as, for example, with jquery - injecting to Flask templates directly :) There are a lot of examples which I do not like, but people do that, for example: http://aviadas.com/blog/2015/08/05/evaluating-react-dot-js-and-flask/

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 41 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#519](https://github.com/timelesslounge/timelessis/issues/519) is not in the agenda of @vryazanov[/z](https://www.0crat.com/u/vryazanov), can't inspect

**Comment by 0crat** [comment]
The job [#519](https://github.com/timelesslounge/timelessis/issues/519) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@vryazanov According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by vryazanov** [comment]
@ypshenychka confirm

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
