### PR TITLE
#147 Readme clarification about Postgres setup

### PR DESCRIPTION
**Pull request by vryazanov**
#147 Small clarification about installing PostgreSQL on local machine

### CODE REVIEW

**Comment by 0crat** [comment]
@vryazanov[/z](https://www.0crat.com/u/vryazanov) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please review this and merge or reject

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#160` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
