### PR TITLE
#15 Item Model + Puzzle

### PR DESCRIPTION
**Pull request by marceloamadeu**
PR for #15 

- Added Item Model
- Left puzzle for continuing implementation
- Migration has not been added since it is not possible to generate.

### CODE REVIEW

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by emilianodellacasa** [comment]
@ypshenychka Do not rate this, but #139

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@emilianodellacasa I don't think it's a good idea to evaluate #139 instead, because @amihaiemil  was not assigned there and thus won't be paid for his work, that was done in scope of this PR. Agree?

**Comment by emilianodellacasa** [comment]
@ypshenychka I could assign #139 to @amihaiemil , but it won't make any difference, you are right. Give feedback on this one then

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

Only cosmetic issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews

**Comment by amihaiemil** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request closed without merging**
