### PR TITLE
#22 User Access Control

### PR DESCRIPTION
**Pull request by Vatavuk**
For #22 . started user access control implementation. Left a lot of puzzles.
The code has already been reviewed in #109

### CODE REVIEW

**Comment by Vatavuk** [comment]
@emilianodellacasa can we merge this?

**Comment by 0crat** [comment]
Job [#152](https://github.com/timelesslounge/timelessis/issues/152) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#152](https://github.com/timelesslounge/timelessis/issues/152) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/e93cd9c0-a81b-465a-8040-657cb499dbc5); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by amihaiemil** [comment]
@rultor code reviewed already, merge

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@vatavuk you have single quotes in your code, please check

**Comment by Vatavuk** [comment]
@emilianodellacasa fixed, sry about the delay.

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@vatavuk check the puzzles

**Comment by Vatavuk** [comment]
@emilianodellacasa fixed, please try again

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 41 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#152](https://github.com/timelesslounge/timelessis/issues/152) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by amihaiemil** [comment]
@ypshenychka Please mark this as "bad" as well, since the review was done in the previous PR.

**Comment by ypshenychka** [comment]
@amihaiemil no problem. Thanks for letting me know!

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
