### PR TITLE
Issue #113 - Adding a puzzle that was wrongly removed

### PR DESCRIPTION
**Pull request by emilianodellacasa**
#113 

Readding a puzzle that was wrongly removed

### CODE REVIEW

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please review this and merge or reject

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#243` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
