### PR TITLE
#97 Implementing Scheme Conditions List view

### PR DESCRIPTION
**Pull request by bkuzmic**
For #97:

- Implementing Scheme Conditions list view by `scheme_type_id`
- Leaving puzzle to implement other views (create, update, delete)
- Fixing tests to run faster (I guess by mistake `conftest.py` was reverted to older code)

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#378](https://github.com/timelesslounge/timelessis/issues/378) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#378](https://github.com/timelesslounge/timelessis/issues/378) is assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/1f379d6c-20c4-40b7-aead-9e8b6c1cf43a); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@bkuzmic I don't see a todo deleted in the PR, also #97 puzzle has no comment!
The PR is fine, I'm just confused

**Comment by bkuzmic** [comment]
@ammaratef45 Thanks, now the puzzle is removed. It is one of the old tickets, that is why pdd didn't format it correctly.

**Comment by ammaratef45** [comment]
@bkuzmic Thanks.
@rultor merge it.

**Comment by ammaratef45** [comment]
@rultor merge it.

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 24 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#378](https://github.com/timelesslounge/timelessis/issues/378) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@ammaratef45  According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

Only one issue was found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by ammaratef45** [comment]
> @ammaratef45 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
> 
> > The code reviewer found at least three problems in the code.
> > Comments were mostly about design problems, not cosmetic issues.
> 
> Only one issue was found during code review.
> Please confirm that you'll try to find at least three major problems while future reviews.

@ypshenychka confirm

**Comment by ypshenychka** [comment]
@ammaratef45 thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +20 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Pull request merged**
