### PR TITLE
#58 Employee Constructor + Pwd Encryption

### PR DESCRIPTION
**Pull request by bkuzmic**
For #58:

- Creating constructor for Employee model which sets defaults fields and encrypts password
- Update tests to reflect changes

### CODE REVIEW

**Comment by emilianodellacasa** [comment]
@bkuzmic Pin code should also be set automatically by the system, using a randomi digit code

**Comment by 0crat** [comment]
Job was finished in 39 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by emilianodellacasa** [comment]
@ypshenychka We had some issues, so I kindly ask you to give quality bad to this one and just consider #138

**Comment by 0crat** [comment]
The job [#122](https://github.com/timelesslounge/timelessis/issues/122) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@emilianodellacasa Ok. I'll consider two code review issues that were found by @amihaiemil  in this ticket in #138.

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request closed without merging**
